// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/config.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	proto "google.golang.org/protobuf/proto"
)

// ConfigAPIToolHandler defines the business logic required by generated MCP tools.
type ConfigAPIToolHandler interface {
	GetClusterConfiguration(ctx context.Context, req *GetClusterConfigurationRequest) (*GetClusterConfigurationResponse, error)
	GetStaticClusterConfiguration(ctx context.Context, req *GetStaticClusterConfigurationRequest) (*GetStaticClusterConfigurationResponse, error)
	UpdateKubernetesVersion(ctx context.Context, req *UpdateKubernetesVersionRequest) (*UpdateKubernetesVersionResponse, error)
}

// RegisterConfigAPITools registers generated MCP tools for ConfigAPI.
func RegisterConfigAPITools(server *mcp.Server, impl ConfigAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterConfigAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*GetClusterConfigurationRequest, *GetClusterConfigurationResponse]{
		Name:             "GetClusterConfiguration",
		Title:            "Get cluster configuration",
		Description:      "Read the full ClusterConfiguration from the d8-cluster-configuration Secret in kube-system. Returns the raw YAML string.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  ConfigAPI_GetClusterConfiguration_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ConfigAPI_GetClusterConfiguration_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *GetClusterConfigurationRequest { return &GetClusterConfigurationRequest{} },
		NewResponse:      func() *GetClusterConfigurationResponse { return &GetClusterConfigurationResponse{} },
		Handler:          impl.GetClusterConfiguration,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*GetStaticClusterConfigurationRequest, *GetStaticClusterConfigurationResponse]{
		Name:             "GetStaticClusterConfiguration",
		Title:            "Get static cluster configuration",
		Description:      "Read the StaticClusterConfiguration YAML from the d8-cluster-configuration Secret in kube-system (key static-cluster-configuration.yaml). Contains internal network CIDR and pod subnet for static cluster setups. Returns an error if the key is absent.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  ConfigAPI_GetStaticClusterConfiguration_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ConfigAPI_GetStaticClusterConfiguration_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *GetStaticClusterConfigurationRequest { return &GetStaticClusterConfigurationRequest{} },
		NewResponse:      func() *GetStaticClusterConfigurationResponse { return &GetStaticClusterConfigurationResponse{} },
		Handler:          impl.GetStaticClusterConfiguration,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*UpdateKubernetesVersionRequest, *UpdateKubernetesVersionResponse]{
		Name:             "UpdateKubernetesVersion",
		Title:            "Update Kubernetes version",
		Description:      "Update the kubernetesVersion field inside the ClusterConfiguration YAML stored in the d8-cluster-configuration Secret. Deckhouse will subsequently upgrade or downgrade the control plane and node components to the requested minor version. Performs a read-modify-write with up to 3 retries on resource conflicts. Use only after consulting the supported versions matrix — invalid values will be rejected by Deckhouse hooks.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  ConfigAPI_UpdateKubernetesVersion_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ConfigAPI_UpdateKubernetesVersion_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *UpdateKubernetesVersionRequest { return &UpdateKubernetesVersionRequest{} },
		NewResponse:      func() *UpdateKubernetesVersionResponse { return &UpdateKubernetesVersionResponse{} },
		Handler:          impl.UpdateKubernetesVersion,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const ConfigAPI_GetClusterConfiguration_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"description\":\"GetClusterConfigurationRequest is empty — no parameters needed.\",\"additionalProperties\":false}"

const ConfigAPI_GetClusterConfiguration_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"configuration\":{\"type\":\"string\",\"description\":\"ClusterConfiguration YAML content from d8-cluster-configuration Secret.\",\"examples\":[\"example\"]}},\"description\":\"ClusterConfiguration read from the cluster Secret.\",\"examples\":[{\"configuration\":\"example\"}],\"required\":[\"configuration\"],\"additionalProperties\":false}"

const ConfigAPI_GetStaticClusterConfiguration_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"description\":\"GetStaticClusterConfigurationRequest is empty — no parameters needed.\",\"additionalProperties\":false}"

const ConfigAPI_GetStaticClusterConfiguration_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"configuration\":{\"type\":\"string\",\"description\":\"StaticClusterConfiguration YAML content from the static-cluster-configuration.yaml key of the d8-cluster-configuration Secret.\",\"examples\":[\"example\"]}},\"description\":\"StaticClusterConfiguration read from the cluster Secret.\",\"examples\":[{\"configuration\":\"example\"}],\"required\":[\"configuration\"],\"additionalProperties\":false}"

const ConfigAPI_UpdateKubernetesVersion_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"version\":{\"type\":\"string\",\"description\":\"Target Kubernetes minor version (MAJOR.MINOR, no patch component). Must be one of the versions supported by the installed Deckhouse release; consult the documentation matrix before submitting.\",\"examples\":[\"1.28\",\"1.29\"],\"minLength\":3,\"pattern\":\"^[0-9]+\\\\.[0-9]+$\"}},\"description\":\"UpdateKubernetesVersionRequest carries the target Kubernetes minor version.\",\"examples\":[{\"version\":\"example\"}],\"required\":[\"version\"],\"additionalProperties\":false}"

const ConfigAPI_UpdateKubernetesVersion_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"previousVersion\":{\"type\":\"string\",\"description\":\"The kubernetesVersion value that was present before the call. Empty if the field was absent.\",\"examples\":[\"1.27\",\"1.28\"]},\"updated\":{\"type\":\"boolean\",\"description\":\"Whether the Secret was successfully patched.\",\"examples\":[true]}},\"description\":\"Result of the UpdateKubernetesVersion operation.\",\"examples\":[{\"previousVersion\":\"example\",\"updated\":true}],\"required\":[\"updated\",\"previousVersion\"],\"additionalProperties\":false}"
