// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/config.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
)

// ConfigAPIToolHandler defines the business logic required by generated MCP tools.
type ConfigAPIToolHandler interface {
	GetClusterConfiguration(ctx context.Context, req *GetClusterConfigurationRequest) (*GetClusterConfigurationResponse, error)
}

// RegisterConfigAPITools registers generated MCP tools for ConfigAPI.
func RegisterConfigAPITools(server *mcp.Server, impl ConfigAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterConfigAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*GetClusterConfigurationRequest, *GetClusterConfigurationResponse]{
		Name:             "GetClusterConfiguration",
		Title:            "Get cluster configuration",
		Description:      "Read the full ClusterConfiguration from the d8-cluster-configuration Secret in kube-system. Returns the raw YAML string.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  ConfigAPI_GetClusterConfiguration_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ConfigAPI_GetClusterConfiguration_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *GetClusterConfigurationRequest { return &GetClusterConfigurationRequest{} },
		NewResponse:      func() *GetClusterConfigurationResponse { return &GetClusterConfigurationResponse{} },
		Handler:          impl.GetClusterConfiguration,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const ConfigAPI_GetClusterConfiguration_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"description\":\"GetClusterConfigurationRequest is empty — no parameters needed.\",\"additionalProperties\":false}"

const ConfigAPI_GetClusterConfiguration_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"configuration\":{\"type\":\"string\",\"description\":\"ClusterConfiguration YAML content from d8-cluster-configuration Secret.\",\"examples\":[\"example\"]}},\"description\":\"ClusterConfiguration read from the cluster Secret.\",\"examples\":[{\"configuration\":\"example\"}],\"required\":[\"configuration\"],\"additionalProperties\":false}"
