// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/nodes.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	proto "google.golang.org/protobuf/proto"
)

// NodesAPIToolHandler defines the business logic required by generated MCP tools.
type NodesAPIToolHandler interface {
	AddWorkerNode(ctx context.Context, req *AddWorkerNodeRequest) (*AddWorkerNodeResponse, error)
	CreateSSHCredentials(ctx context.Context, req *CreateSSHCredentialsRequest) (*CreateSSHCredentialsResponse, error)
	CreateStaticInstance(ctx context.Context, req *CreateStaticInstanceRequest) (*CreateStaticInstanceResponse, error)
	DeleteStaticInstance(ctx context.Context, req *DeleteStaticInstanceRequest) (*DeleteStaticInstanceResponse, error)
	RemoveNode(ctx context.Context, req *RemoveNodeRequest) (*RemoveNodeResponse, error)
	CreateNodeGroup(ctx context.Context, req *CreateNodeGroupRequest) (*CreateNodeGroupResponse, error)
	WaitNodeReady(ctx context.Context, req *WaitNodeReadyRequest) (*WaitNodeReadyResponse, error)
	CordonNode(ctx context.Context, req *CordonNodeRequest) (*CordonNodeResponse, error)
	UncordonNode(ctx context.Context, req *UncordonNodeRequest) (*UncordonNodeResponse, error)
	DrainNode(ctx context.Context, req *DrainNodeRequest) (*DrainNodeResponse, error)
	DeleteSSHCredentials(ctx context.Context, req *DeleteSSHCredentialsRequest) (*DeleteSSHCredentialsResponse, error)
	DeleteNodeGroup(ctx context.Context, req *DeleteNodeGroupRequest) (*DeleteNodeGroupResponse, error)
}

// RegisterNodesAPITools registers generated MCP tools for NodesAPI.
func RegisterNodesAPITools(server *mcp.Server, impl NodesAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterNodesAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*AddWorkerNodeRequest, *AddWorkerNodeResponse]{
		Name:             "AddWorkerNode",
		Title:            "Add worker node",
		Description:      "Composite operation that adds a bare-metal server as a Deckhouse worker node. Steps: (1) create SSHCredentials with the provided key, (2) create StaticInstance bound to that credential and the target NodeGroup. If wait_ready is true (default), polls every 30s until the StaticInstance reaches Running phase or the timeout expires — returns last observed phase and timed_out flag. If step 1 fails, step 2 is not attempted. If step 2 fails, the SSHCredentials resource from step 1 still exists.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_AddWorkerNode_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_AddWorkerNode_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *AddWorkerNodeRequest { return &AddWorkerNodeRequest{} },
		NewResponse:      func() *AddWorkerNodeResponse { return &AddWorkerNodeResponse{} },
		Handler:          impl.AddWorkerNode,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateSSHCredentialsRequest, *CreateSSHCredentialsResponse]{
		Name:             "CreateSSHCredentials",
		Title:            "Create SSH credentials",
		Description:      "Create an SSHCredentials resource in the d8-system namespace. The private key must be in PEM format (RSA, ED25519, or ECDSA); it is base64-encoded internally before storing in the Kubernetes Secret. The sudo_password field is optional and only needed when the remote user requires a password for sudo.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_CreateSSHCredentials_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_CreateSSHCredentials_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *CreateSSHCredentialsRequest { return &CreateSSHCredentialsRequest{} },
		NewResponse:      func() *CreateSSHCredentialsResponse { return &CreateSSHCredentialsResponse{} },
		Handler:          impl.CreateSSHCredentials,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateStaticInstanceRequest, *CreateStaticInstanceResponse]{
		Name:             "CreateStaticInstance",
		Title:            "Create static instance",
		Description:      "Create a StaticInstance resource bound to SSHCredentials via credentialsRef.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_CreateStaticInstance_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_CreateStaticInstance_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *CreateStaticInstanceRequest { return &CreateStaticInstanceRequest{} },
		NewResponse:      func() *CreateStaticInstanceResponse { return &CreateStaticInstanceResponse{} },
		Handler:          impl.CreateStaticInstance,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*DeleteStaticInstanceRequest, *DeleteStaticInstanceResponse]{
		Name:             "DeleteStaticInstance",
		Title:            "Delete static instance",
		Description:      "Delete a StaticInstance resource by name. Deckhouse will gracefully clean up the node.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_DeleteStaticInstance_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_DeleteStaticInstance_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *DeleteStaticInstanceRequest { return &DeleteStaticInstanceRequest{} },
		NewResponse:      func() *DeleteStaticInstanceResponse { return &DeleteStaticInstanceResponse{} },
		Handler:          impl.DeleteStaticInstance,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*RemoveNodeRequest, *RemoveNodeResponse]{
		Name:             "RemoveNode",
		Title:            "Remove node",
		Description:      "Composite: cordon the node, evict all non-DaemonSet pods, then delete the associated StaticInstance. Returns error if no StaticInstance is found for the node (static nodes only).",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_RemoveNode_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_RemoveNode_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *RemoveNodeRequest { return &RemoveNodeRequest{} },
		NewResponse:      func() *RemoveNodeResponse { return &RemoveNodeResponse{} },
		Handler:          impl.RemoveNode,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateNodeGroupRequest, *CreateNodeGroupResponse]{
		Name:             "CreateNodeGroup",
		Title:            "Create node group",
		Description:      "Create a new NodeGroup resource. In Deckhouse CE only 'Static' nodeType is supported.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_CreateNodeGroup_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_CreateNodeGroup_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *CreateNodeGroupRequest { return &CreateNodeGroupRequest{} },
		NewResponse:      func() *CreateNodeGroupResponse { return &CreateNodeGroupResponse{} },
		Handler:          impl.CreateNodeGroup,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*WaitNodeReadyRequest, *WaitNodeReadyResponse]{
		Name:             "WaitNodeReady",
		Title:            "Wait node ready",
		Description:      "Poll StaticInstance.status.currentStatus.phase until it reaches 'Running' or timeout. Returns the final phase, elapsed time, and whether timeout occurred.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_WaitNodeReady_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_WaitNodeReady_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *WaitNodeReadyRequest { return &WaitNodeReadyRequest{} },
		NewResponse:      func() *WaitNodeReadyResponse { return &WaitNodeReadyResponse{} },
		Handler:          impl.WaitNodeReady,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CordonNodeRequest, *CordonNodeResponse]{
		Name:             "CordonNode",
		Title:            "Cordon node",
		Description:      "Mark a node as unschedulable by setting spec.unschedulable=true. New pods will not be scheduled onto it. Returns the previous unschedulable state. Idempotent — safe to call on an already-cordoned node.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_CordonNode_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_CordonNode_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{IdempotentHint: true},
		Icons:            nil,
		NewRequest:       func() *CordonNodeRequest { return &CordonNodeRequest{} },
		NewResponse:      func() *CordonNodeResponse { return &CordonNodeResponse{} },
		Handler:          impl.CordonNode,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*UncordonNodeRequest, *UncordonNodeResponse]{
		Name:             "UncordonNode",
		Title:            "Uncordon node",
		Description:      "Mark a node as schedulable by setting spec.unschedulable=false. Returns the previous unschedulable state. Idempotent — safe to call on a non-cordoned node.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_UncordonNode_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_UncordonNode_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{IdempotentHint: true},
		Icons:            nil,
		NewRequest:       func() *UncordonNodeRequest { return &UncordonNodeRequest{} },
		NewResponse:      func() *UncordonNodeResponse { return &UncordonNodeResponse{} },
		Handler:          impl.UncordonNode,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*DrainNodeRequest, *DrainNodeResponse]{
		Name:             "DrainNode",
		Title:            "Drain node",
		Description:      "Composite operation: (1) cordon the node, (2) iteratively evict every non-DaemonSet, non-mirror pod via the Kubernetes Eviction API (policy/v1), respecting PodDisruptionBudgets. Polls every 30s until all evictable pods are gone or the timeout expires. DaemonSet-managed pods and mirror pods are skipped. Returns the number of pods evicted, any pods that failed eviction, and timed_out flag. The node remains cordoned after the call.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_DrainNode_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_DrainNode_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *DrainNodeRequest { return &DrainNodeRequest{} },
		NewResponse:      func() *DrainNodeResponse { return &DrainNodeResponse{} },
		Handler:          impl.DrainNode,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*DeleteSSHCredentialsRequest, *DeleteSSHCredentialsResponse]{
		Name:             "DeleteSSHCredentials",
		Title:            "Delete SSH credentials",
		Description:      "Delete an SSHCredentials resource by name. Any StaticInstance still referencing it via credentialsRef will become unable to authenticate to its server.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_DeleteSSHCredentials_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_DeleteSSHCredentials_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *DeleteSSHCredentialsRequest { return &DeleteSSHCredentialsRequest{} },
		NewResponse:      func() *DeleteSSHCredentialsResponse { return &DeleteSSHCredentialsResponse{} },
		Handler:          impl.DeleteSSHCredentials,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*DeleteNodeGroupRequest, *DeleteNodeGroupResponse]{
		Name:             "DeleteNodeGroup",
		Title:            "Delete node group",
		Description:      "Delete a NodeGroup resource by name. StaticInstance resources belonging to the group will no longer be managed; nodes that have already joined the cluster keep their kubelet running but lose their NodeGroup affiliation.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_DeleteNodeGroup_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_DeleteNodeGroup_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *DeleteNodeGroupRequest { return &DeleteNodeGroupRequest{} },
		NewResponse:      func() *DeleteNodeGroupResponse { return &DeleteNodeGroupResponse{} },
		Handler:          impl.DeleteNodeGroup,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const NodesAPI_AddWorkerNode_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"address\":{\"type\":\"string\",\"description\":\"IP address of the server to add.\",\"examples\":[\"192.168.1.100\"],\"format\":\"ipv4\"},\"nodeGroup\":{\"type\":\"string\",\"description\":\"Name of the target NodeGroup. Must be an existing NodeGroup with nodeType: Static.\",\"examples\":[\"worker\"]},\"nodeName\":{\"type\":[\"string\",\"null\"],\"description\":\"Name for the node. If omitted, generated from IP address (dots replaced with dashes, e.g. 192-168-1-100).\",\"examples\":[\"worker-1\"]},\"privateKey\":{\"type\":\"string\",\"description\":\"Private SSH key in PEM format (RSA, ED25519, or ECDSA). Must NOT be base64-encoded — encoding is done internally.\",\"examples\":[\"-----BEGIN OPENSSH PRIVATE KEY-----\\n...\"]},\"sshPort\":{\"type\":[\"integer\",\"null\"],\"description\":\"SSH port. Default: 22.\",\"default\":22,\"examples\":[-1],\"minimum\":1,\"maximum\":65535},\"sshUser\":{\"type\":\"string\",\"description\":\"SSH username for connecting to the server.\",\"examples\":[\"ubuntu\",\"root\"]},\"timeoutSeconds\":{\"type\":[\"integer\",\"null\"],\"description\":\"Timeout in seconds for waiting. Default: 900 (15 minutes). Ignored when wait_ready is false.\",\"default\":900,\"examples\":[-1],\"minimum\":1,\"maximum\":3600},\"waitReady\":{\"type\":[\"boolean\",\"null\"],\"description\":\"Wait for the StaticInstance to reach Running phase. Default: true. When false, returns immediately after creating resources.\",\"default\":true,\"examples\":[true]}},\"description\":\"AddWorkerNodeRequest contains parameters for the composite add-node operation.\",\"examples\":[{\"address\":\"example\",\"nodeGroup\":\"example\",\"nodeName\":\"example\",\"privateKey\":\"example\",\"sshPort\":-1,\"sshUser\":\"example\",\"timeoutSeconds\":-1,\"waitReady\":true}],\"required\":[\"address\",\"sshUser\",\"privateKey\",\"nodeGroup\"],\"additionalProperties\":false}"

const NodesAPI_AddWorkerNode_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"elapsed\":{\"type\":\"string\",\"description\":\"Wall-clock time spent waiting (e.g. 45s, 2m30s). Empty if waitReady was false.\",\"examples\":[\"45s\",\"2m30s\"]},\"nodeName\":{\"type\":\"string\",\"description\":\"Name assigned to the node.\",\"examples\":[\"example\"]},\"phase\":{\"type\":\"string\",\"description\":\"Final observed phase of the StaticInstance: Pending, Bootstrapping, Running, or Error.\",\"examples\":[\"Running\",\"Pending\"]},\"sshCredentialsName\":{\"type\":\"string\",\"description\":\"Name of the created SSHCredentials resource.\",\"examples\":[\"example\"]},\"staticInstanceName\":{\"type\":\"string\",\"description\":\"Name of the created StaticInstance resource.\",\"examples\":[\"example\"]},\"timedOut\":{\"type\":\"boolean\",\"description\":\"True if the operation timed out before the StaticInstance reached Running phase.\",\"examples\":[true]}},\"description\":\"Result of the composite AddWorkerNode operation.\",\"examples\":[{\"elapsed\":\"example\",\"nodeName\":\"example\",\"phase\":\"example\",\"sshCredentialsName\":\"example\",\"staticInstanceName\":\"example\",\"timedOut\":true}],\"required\":[\"nodeName\",\"sshCredentialsName\",\"staticInstanceName\",\"phase\",\"elapsed\",\"timedOut\"],\"additionalProperties\":false}"

const NodesAPI_CreateSSHCredentials_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the SSHCredentials resource.\",\"examples\":[\"worker-1-ssh\"]},\"port\":{\"type\":[\"integer\",\"null\"],\"description\":\"SSH port. Default: 22.\",\"default\":22,\"examples\":[-1],\"minimum\":1,\"maximum\":65535},\"privateKey\":{\"type\":\"string\",\"description\":\"Private SSH key in PEM format (RSA, ED25519, or ECDSA). Base64 encoding is done internally.\",\"examples\":[\"-----BEGIN OPENSSH PRIVATE KEY-----\\n...\"]},\"sshExtraArgs\":{\"type\":[\"string\",\"null\"],\"description\":\"Additional SSH client arguments (e.g. -o StrictHostKeyChecking=no).\",\"examples\":[\"-o StrictHostKeyChecking=no\"]},\"sudoPassword\":{\"type\":[\"string\",\"null\"],\"description\":\"Sudo password. Only required when the remote SSH user needs a password for sudo privilege escalation.\",\"examples\":[\"example\"]},\"user\":{\"type\":\"string\",\"description\":\"SSH username for connecting to the server.\",\"examples\":[\"ubuntu\",\"root\"]}},\"description\":\"CreateSSHCredentialsRequest contains parameters for SSHCredentials creation.\",\"examples\":[{\"name\":\"example\",\"port\":-1,\"privateKey\":\"example\",\"sshExtraArgs\":\"example\",\"sudoPassword\":\"example\",\"user\":\"example\"}],\"required\":[\"name\",\"user\",\"privateKey\"],\"additionalProperties\":false}"

const NodesAPI_CreateSSHCredentials_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the created SSHCredentials resource.\",\"examples\":[\"example\"]}},\"description\":\"Result of SSHCredentials creation.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_CreateStaticInstance_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"address\":{\"type\":\"string\",\"description\":\"IP address of the server.\",\"examples\":[\"192.168.1.100\"],\"format\":\"ipv4\"},\"credentialsRef\":{\"type\":\"string\",\"description\":\"Name of the SSHCredentials resource to reference. Must exist in d8-system namespace.\",\"examples\":[\"worker-1-ssh\"]},\"labels\":{\"type\":[\"object\",\"null\"],\"description\":\"Labels for binding to NodeGroup via labelSelector. Must match the NodeGroup's nodeSelector.\",\"examples\":[{\"key\":\"example\"}],\"additionalProperties\":{\"type\":\"string\"},\"propertyNames\":{\"type\":\"string\"}},\"name\":{\"type\":\"string\",\"description\":\"Name of the StaticInstance.\",\"examples\":[\"worker-1\"]}},\"description\":\"CreateStaticInstanceRequest contains parameters for StaticInstance creation.\",\"examples\":[{\"address\":\"example\",\"credentialsRef\":\"example\",\"labels\":{\"key\":\"example\"},\"name\":\"example\"}],\"required\":[\"name\",\"address\",\"credentialsRef\"],\"additionalProperties\":false}"

const NodesAPI_CreateStaticInstance_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"address\":{\"type\":\"string\",\"description\":\"IP address of the server.\",\"examples\":[\"example\"],\"format\":\"ipv4\"},\"credentialsRef\":{\"type\":\"string\",\"description\":\"Name of the referenced SSHCredentials resource.\",\"examples\":[\"example\"]},\"labels\":{\"type\":[\"object\",\"null\"],\"description\":\"Labels applied to the StaticInstance for NodeGroup binding.\",\"examples\":[{\"key\":\"example\"}],\"additionalProperties\":{\"type\":\"string\"},\"propertyNames\":{\"type\":\"string\"}},\"name\":{\"type\":\"string\",\"description\":\"Name of the created StaticInstance resource.\",\"examples\":[\"example\"]}},\"description\":\"Result of StaticInstance creation.\",\"examples\":[{\"address\":\"example\",\"credentialsRef\":\"example\",\"labels\":{\"key\":\"example\"},\"name\":\"example\"}],\"required\":[\"name\",\"address\",\"credentialsRef\"],\"additionalProperties\":false}"

const NodesAPI_DeleteStaticInstance_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the StaticInstance resource to delete.\",\"examples\":[\"worker-01\"],\"minLength\":1}},\"description\":\"DeleteStaticInstanceRequest contains the name of the StaticInstance to delete.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_DeleteStaticInstance_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"success\":{\"type\":\"boolean\",\"description\":\"Whether the deletion succeeded.\",\"examples\":[true]}},\"description\":\"DeleteStaticInstanceResponse contains the result of deletion.\",\"examples\":[{\"success\":true}],\"required\":[\"success\"],\"additionalProperties\":false}"

const NodesAPI_RemoveNode_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"drain\":{\"type\":[\"boolean\",\"null\"],\"description\":\"Cordon and evict pods before deleting the StaticInstance. Default: true.\",\"default\":true,\"examples\":[true]},\"name\":{\"type\":\"string\",\"description\":\"Name of the Node (and StaticInstance) to remove.\",\"examples\":[\"worker-01\"],\"minLength\":1}},\"description\":\"RemoveNodeRequest contains the node name and drain options.\",\"examples\":[{\"drain\":true,\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_RemoveNode_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"deleted\":{\"type\":\"boolean\",\"description\":\"Whether the StaticInstance was deleted.\",\"examples\":[true]},\"drained\":{\"type\":\"boolean\",\"description\":\"Whether the node was cordoned and pods were evicted.\",\"examples\":[true]}},\"description\":\"Result of the composite RemoveNode operation.\",\"examples\":[{\"deleted\":true,\"drained\":true}],\"required\":[\"drained\",\"deleted\"],\"additionalProperties\":false}"

const NodesAPI_CreateNodeGroup_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"count\":{\"type\":[\"integer\",\"null\"],\"description\":\"Desired number of nodes in the group.\",\"examples\":[-1],\"minimum\":0},\"disruptions\":{\"type\":[\"string\",\"null\"],\"description\":\"Disruption approval mode: 'Automatic' or 'Manual'. Default: Automatic.\",\"examples\":[\"Automatic\",\"Manual\"]},\"labels\":{\"type\":[\"object\",\"null\"],\"description\":\"Labels to apply to Node objects in this group.\",\"examples\":[{\"key\":\"example\"}],\"additionalProperties\":{\"type\":\"string\"},\"propertyNames\":{\"type\":\"string\"}},\"maxPodsPerNode\":{\"type\":[\"integer\",\"null\"],\"description\":\"Maximum pods per node. Default: 110.\",\"examples\":[-1],\"minimum\":1,\"maximum\":500},\"name\":{\"type\":\"string\",\"description\":\"Name of the NodeGroup resource.\",\"examples\":[\"workers\"],\"minLength\":1},\"nodeType\":{\"type\":\"string\",\"description\":\"Node type: 'Static' (CE only), 'CloudEphemeral', 'CloudPermanent', or 'CloudStatic'.\",\"examples\":[\"Static\"],\"minLength\":1}},\"description\":\"CreateNodeGroupRequest contains parameters for NodeGroup creation.\",\"examples\":[{\"count\":-1,\"disruptions\":\"example\",\"labels\":{\"key\":\"example\"},\"maxPodsPerNode\":-1,\"name\":\"example\",\"nodeType\":\"example\"}],\"required\":[\"name\",\"nodeType\"],\"additionalProperties\":false}"

const NodesAPI_CreateNodeGroup_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"count\":{\"type\":[\"integer\",\"null\"],\"description\":\"Desired node count.\",\"examples\":[-1],\"minimum\":0},\"name\":{\"type\":\"string\",\"description\":\"Name of the created NodeGroup.\",\"examples\":[\"example\"]},\"nodeType\":{\"type\":\"string\",\"description\":\"Node type of the created NodeGroup.\",\"examples\":[\"example\"]}},\"description\":\"Result of NodeGroup creation.\",\"examples\":[{\"count\":-1,\"name\":\"example\",\"nodeType\":\"example\"}],\"required\":[\"name\",\"nodeType\"],\"additionalProperties\":false}"

const NodesAPI_WaitNodeReady_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"intervalSeconds\":{\"type\":[\"integer\",\"null\"],\"description\":\"Polling interval in seconds. Default: 30.\",\"examples\":[-1],\"minimum\":5,\"maximum\":300},\"name\":{\"type\":\"string\",\"description\":\"Name of the StaticInstance to wait for.\",\"examples\":[\"worker-01\"],\"minLength\":1},\"timeoutSeconds\":{\"type\":[\"integer\",\"null\"],\"description\":\"Maximum wait time in seconds. Default: 900.\",\"examples\":[-1],\"minimum\":30,\"maximum\":3600}},\"description\":\"WaitNodeReadyRequest contains the node/StaticInstance name and polling options.\",\"examples\":[{\"intervalSeconds\":-1,\"name\":\"example\",\"timeoutSeconds\":-1}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_WaitNodeReady_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"elapsed\":{\"type\":\"string\",\"description\":\"Wall-clock time spent polling (e.g. '45s', '2m30s').\",\"examples\":[\"45s\",\"2m30s\"]},\"phase\":{\"type\":\"string\",\"description\":\"Final observed phase of the StaticInstance.\",\"examples\":[\"Running\",\"Bootstrapping\"]},\"timedOut\":{\"type\":\"boolean\",\"description\":\"True if the polling timed out before reaching Running phase.\",\"examples\":[true]}},\"description\":\"Result of polling StaticInstance until Running or timeout.\",\"examples\":[{\"elapsed\":\"example\",\"phase\":\"example\",\"timedOut\":true}],\"required\":[\"phase\",\"elapsed\",\"timedOut\"],\"additionalProperties\":false}"

const NodesAPI_CordonNode_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the Node to cordon.\",\"examples\":[\"worker-01\"],\"minLength\":1}},\"description\":\"CordonNodeRequest contains the node name to cordon.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_CordonNode_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"previousState\":{\"type\":\"boolean\",\"description\":\"Previous value of spec.unschedulable before this call. True means the node was already cordoned.\",\"examples\":[true]}},\"description\":\"Result of the cordon node operation.\",\"examples\":[{\"previousState\":true}],\"required\":[\"previousState\"],\"additionalProperties\":false}"

const NodesAPI_UncordonNode_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the Node to uncordon.\",\"examples\":[\"worker-01\"],\"minLength\":1}},\"description\":\"UncordonNodeRequest contains the node name to uncordon.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_UncordonNode_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"previousState\":{\"type\":\"boolean\",\"description\":\"Previous value of spec.unschedulable before this call. True means the node was cordoned before this call.\",\"examples\":[true]}},\"description\":\"Result of the uncordon node operation.\",\"examples\":[{\"previousState\":true}],\"required\":[\"previousState\"],\"additionalProperties\":false}"

const NodesAPI_DrainNode_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the Node to drain.\",\"examples\":[\"worker-01\"],\"minLength\":1},\"timeoutSeconds\":{\"type\":[\"integer\",\"null\"],\"description\":\"Maximum wall-clock time in seconds the drain may take. Default: 300.\",\"examples\":[-1],\"minimum\":30,\"maximum\":3600}},\"description\":\"DrainNodeRequest contains the node name and polling options.\",\"examples\":[{\"name\":\"example\",\"timeoutSeconds\":-1}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_DrainNode_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"cordoned\":{\"type\":\"boolean\",\"description\":\"Whether the cordon step succeeded. False means the drain was aborted at step 1.\",\"examples\":[true]},\"elapsed\":{\"type\":\"string\",\"description\":\"Wall-clock time spent draining (e.g. '45s', '2m30s').\",\"examples\":[\"45s\",\"2m30s\"]},\"evictedCount\":{\"type\":\"integer\",\"description\":\"Number of pods successfully evicted (or that disappeared during the loop).\",\"examples\":[-1],\"minimum\":0},\"failedPods\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"description\":\"Pods that failed eviction with a non-recoverable error. Format: namespace/name.\",\"examples\":[\"example\"]},\"description\":\"Pods that failed eviction with a non-recoverable error. Format: namespace/name.\",\"examples\":[\"default/web-7f8d-abc\"]},\"timedOut\":{\"type\":\"boolean\",\"description\":\"True if the timeout expired before all evictable pods were removed.\",\"examples\":[true]}},\"description\":\"Outcome of the DrainNode operation.\",\"examples\":[{\"cordoned\":true,\"elapsed\":\"example\",\"evictedCount\":-1,\"failedPods\":[\"example\"],\"timedOut\":true}],\"required\":[\"cordoned\",\"evictedCount\",\"timedOut\",\"elapsed\"],\"additionalProperties\":false}"

const NodesAPI_DeleteSSHCredentials_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the SSHCredentials resource to delete.\",\"examples\":[\"creds-worker-01\"],\"minLength\":1}},\"description\":\"DeleteSSHCredentialsRequest contains the SSHCredentials name to delete.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_DeleteSSHCredentials_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"deleted\":{\"type\":\"boolean\",\"description\":\"Whether the resource was deleted.\",\"examples\":[true]}},\"description\":\"Result of the DeleteSSHCredentials operation.\",\"examples\":[{\"deleted\":true}],\"required\":[\"deleted\"],\"additionalProperties\":false}"

const NodesAPI_DeleteNodeGroup_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the NodeGroup resource to delete.\",\"examples\":[\"worker\",\"static-workers\"],\"minLength\":1}},\"description\":\"DeleteNodeGroupRequest contains the NodeGroup name to delete.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_DeleteNodeGroup_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"deleted\":{\"type\":\"boolean\",\"description\":\"Whether the resource was deleted.\",\"examples\":[true]}},\"description\":\"Result of the DeleteNodeGroup operation.\",\"examples\":[{\"deleted\":true}],\"required\":[\"deleted\"],\"additionalProperties\":false}"
