// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/nodes.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	proto "google.golang.org/protobuf/proto"
)

// NodesAPIToolHandler defines the business logic required by generated MCP tools.
type NodesAPIToolHandler interface {
	AddWorkerNode(ctx context.Context, req *AddWorkerNodeRequest) (*AddWorkerNodeResponse, error)
	CreateSSHCredentials(ctx context.Context, req *CreateSSHCredentialsRequest) (*CreateSSHCredentialsResponse, error)
	CreateStaticInstance(ctx context.Context, req *CreateStaticInstanceRequest) (*CreateStaticInstanceResponse, error)
}

// RegisterNodesAPITools registers generated MCP tools for NodesAPI.
func RegisterNodesAPITools(server *mcp.Server, impl NodesAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterNodesAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*AddWorkerNodeRequest, *AddWorkerNodeResponse]{
		Name:             "AddWorkerNode",
		Title:            "Add worker node",
		Description:      "Composite operation that adds a bare-metal server as a Deckhouse worker node. Steps: (1) create SSHCredentials with the provided key, (2) create StaticInstance bound to that credential and the target NodeGroup. If wait_ready is true (default), polls every 30s until the StaticInstance reaches Running phase or the timeout expires — returns last observed phase and timed_out flag. If step 1 fails, step 2 is not attempted. If step 2 fails, the SSHCredentials resource from step 1 still exists.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_AddWorkerNode_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_AddWorkerNode_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *AddWorkerNodeRequest { return &AddWorkerNodeRequest{} },
		NewResponse:      func() *AddWorkerNodeResponse { return &AddWorkerNodeResponse{} },
		Handler:          impl.AddWorkerNode,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateSSHCredentialsRequest, *CreateSSHCredentialsResponse]{
		Name:             "CreateSSHCredentials",
		Title:            "Create SSH credentials",
		Description:      "Create an SSHCredentials resource in the d8-system namespace. The private key must be in PEM format (RSA, ED25519, or ECDSA); it is base64-encoded internally before storing in the Kubernetes Secret. The sudo_password field is optional and only needed when the remote user requires a password for sudo.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_CreateSSHCredentials_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_CreateSSHCredentials_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *CreateSSHCredentialsRequest { return &CreateSSHCredentialsRequest{} },
		NewResponse:      func() *CreateSSHCredentialsResponse { return &CreateSSHCredentialsResponse{} },
		Handler:          impl.CreateSSHCredentials,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateStaticInstanceRequest, *CreateStaticInstanceResponse]{
		Name:             "CreateStaticInstance",
		Title:            "Create static instance",
		Description:      "Create a StaticInstance resource bound to SSHCredentials via credentialsRef.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  NodesAPI_CreateStaticInstance_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: NodesAPI_CreateStaticInstance_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *CreateStaticInstanceRequest { return &CreateStaticInstanceRequest{} },
		NewResponse:      func() *CreateStaticInstanceResponse { return &CreateStaticInstanceResponse{} },
		Handler:          impl.CreateStaticInstance,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const NodesAPI_AddWorkerNode_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"address\":{\"type\":\"string\",\"description\":\"IP address of the server to add.\",\"examples\":[\"192.168.1.100\"],\"format\":\"ipv4\"},\"nodeGroup\":{\"type\":\"string\",\"description\":\"Name of the target NodeGroup. Must be an existing NodeGroup with nodeType: Static.\",\"examples\":[\"worker\"]},\"nodeName\":{\"type\":[\"string\",\"null\"],\"description\":\"Name for the node. If omitted, generated from IP address (dots replaced with dashes, e.g. 192-168-1-100).\",\"examples\":[\"worker-1\"]},\"privateKey\":{\"type\":\"string\",\"description\":\"Private SSH key in PEM format (RSA, ED25519, or ECDSA). Must NOT be base64-encoded — encoding is done internally.\",\"examples\":[\"-----BEGIN OPENSSH PRIVATE KEY-----\\n...\"]},\"sshPort\":{\"type\":[\"integer\",\"null\"],\"description\":\"SSH port. Default: 22.\",\"default\":22,\"examples\":[-1],\"minimum\":1,\"maximum\":65535},\"sshUser\":{\"type\":\"string\",\"description\":\"SSH username for connecting to the server.\",\"examples\":[\"ubuntu\",\"root\"]},\"timeoutSeconds\":{\"type\":[\"integer\",\"null\"],\"description\":\"Timeout in seconds for waiting. Default: 900 (15 minutes). Ignored when wait_ready is false.\",\"default\":900,\"examples\":[-1],\"minimum\":1,\"maximum\":3600},\"waitReady\":{\"type\":[\"boolean\",\"null\"],\"description\":\"Wait for the StaticInstance to reach Running phase. Default: true. When false, returns immediately after creating resources.\",\"default\":true,\"examples\":[true]}},\"description\":\"AddWorkerNodeRequest contains parameters for the composite add-node operation.\",\"examples\":[{\"address\":\"example\",\"nodeGroup\":\"example\",\"nodeName\":\"example\",\"privateKey\":\"example\",\"sshPort\":-1,\"sshUser\":\"example\",\"timeoutSeconds\":-1,\"waitReady\":true}],\"required\":[\"address\",\"sshUser\",\"privateKey\",\"nodeGroup\"],\"additionalProperties\":false}"

const NodesAPI_AddWorkerNode_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"elapsed\":{\"type\":\"string\",\"description\":\"Wall-clock time spent waiting (e.g. 45s, 2m30s). Empty if waitReady was false.\",\"examples\":[\"45s\",\"2m30s\"]},\"nodeName\":{\"type\":\"string\",\"description\":\"Name assigned to the node.\",\"examples\":[\"example\"]},\"phase\":{\"type\":\"string\",\"description\":\"Final observed phase of the StaticInstance: Pending, Bootstrapping, Running, or Error.\",\"examples\":[\"Running\",\"Pending\"]},\"sshCredentialsName\":{\"type\":\"string\",\"description\":\"Name of the created SSHCredentials resource.\",\"examples\":[\"example\"]},\"staticInstanceName\":{\"type\":\"string\",\"description\":\"Name of the created StaticInstance resource.\",\"examples\":[\"example\"]},\"timedOut\":{\"type\":\"boolean\",\"description\":\"True if the operation timed out before the StaticInstance reached Running phase.\",\"examples\":[true]}},\"description\":\"Result of the composite AddWorkerNode operation.\",\"examples\":[{\"elapsed\":\"example\",\"nodeName\":\"example\",\"phase\":\"example\",\"sshCredentialsName\":\"example\",\"staticInstanceName\":\"example\",\"timedOut\":true}],\"required\":[\"nodeName\",\"sshCredentialsName\",\"staticInstanceName\",\"phase\",\"elapsed\",\"timedOut\"],\"additionalProperties\":false}"

const NodesAPI_CreateSSHCredentials_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the SSHCredentials resource.\",\"examples\":[\"worker-1-ssh\"]},\"port\":{\"type\":[\"integer\",\"null\"],\"description\":\"SSH port. Default: 22.\",\"default\":22,\"examples\":[-1],\"minimum\":1,\"maximum\":65535},\"privateKey\":{\"type\":\"string\",\"description\":\"Private SSH key in PEM format (RSA, ED25519, or ECDSA). Base64 encoding is done internally.\",\"examples\":[\"-----BEGIN OPENSSH PRIVATE KEY-----\\n...\"]},\"sshExtraArgs\":{\"type\":[\"string\",\"null\"],\"description\":\"Additional SSH client arguments (e.g. -o StrictHostKeyChecking=no).\",\"examples\":[\"-o StrictHostKeyChecking=no\"]},\"sudoPassword\":{\"type\":[\"string\",\"null\"],\"description\":\"Sudo password. Only required when the remote SSH user needs a password for sudo privilege escalation.\",\"examples\":[\"example\"]},\"user\":{\"type\":\"string\",\"description\":\"SSH username for connecting to the server.\",\"examples\":[\"ubuntu\",\"root\"]}},\"description\":\"CreateSSHCredentialsRequest contains parameters for SSHCredentials creation.\",\"examples\":[{\"name\":\"example\",\"port\":-1,\"privateKey\":\"example\",\"sshExtraArgs\":\"example\",\"sudoPassword\":\"example\",\"user\":\"example\"}],\"required\":[\"name\",\"user\",\"privateKey\"],\"additionalProperties\":false}"

const NodesAPI_CreateSSHCredentials_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"Name of the created SSHCredentials resource.\",\"examples\":[\"example\"]}},\"description\":\"Result of SSHCredentials creation.\",\"examples\":[{\"name\":\"example\"}],\"required\":[\"name\"],\"additionalProperties\":false}"

const NodesAPI_CreateStaticInstance_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"address\":{\"type\":\"string\",\"description\":\"IP address of the server.\",\"examples\":[\"192.168.1.100\"],\"format\":\"ipv4\"},\"credentialsRef\":{\"type\":\"string\",\"description\":\"Name of the SSHCredentials resource to reference. Must exist in d8-system namespace.\",\"examples\":[\"worker-1-ssh\"]},\"labels\":{\"type\":[\"object\",\"null\"],\"description\":\"Labels for binding to NodeGroup via labelSelector. Must match the NodeGroup's nodeSelector.\",\"examples\":[{\"key\":\"example\"}],\"additionalProperties\":{\"type\":\"string\"},\"propertyNames\":{\"type\":\"string\"}},\"name\":{\"type\":\"string\",\"description\":\"Name of the StaticInstance.\",\"examples\":[\"worker-1\"]}},\"description\":\"CreateStaticInstanceRequest contains parameters for StaticInstance creation.\",\"examples\":[{\"address\":\"example\",\"credentialsRef\":\"example\",\"labels\":{\"key\":\"example\"},\"name\":\"example\"}],\"required\":[\"name\",\"address\",\"credentialsRef\"],\"additionalProperties\":false}"

const NodesAPI_CreateStaticInstance_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"address\":{\"type\":\"string\",\"description\":\"IP address of the server.\",\"examples\":[\"example\"],\"format\":\"ipv4\"},\"credentialsRef\":{\"type\":\"string\",\"description\":\"Name of the referenced SSHCredentials resource.\",\"examples\":[\"example\"]},\"labels\":{\"type\":[\"object\",\"null\"],\"description\":\"Labels applied to the StaticInstance for NodeGroup binding.\",\"examples\":[{\"key\":\"example\"}],\"additionalProperties\":{\"type\":\"string\"},\"propertyNames\":{\"type\":\"string\"}},\"name\":{\"type\":\"string\",\"description\":\"Name of the created StaticInstance resource.\",\"examples\":[\"example\"]}},\"description\":\"Result of StaticInstance creation.\",\"examples\":[{\"address\":\"example\",\"credentialsRef\":\"example\",\"labels\":{\"key\":\"example\"},\"name\":\"example\"}],\"required\":[\"name\",\"address\",\"credentialsRef\"],\"additionalProperties\":false}"
