// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/deckhouse/v1/sources.proto

package deckhousev1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
)

// SourcesAPIToolHandler defines the business logic required by generated MCP tools.
type SourcesAPIToolHandler interface {
	ListModuleSources(ctx context.Context, req *ListModuleSourcesRequest) (*ListModuleSourcesResponse, error)
	CreateModuleSource(ctx context.Context, req *CreateModuleSourceRequest) (*CreateModuleSourceResponse, error)
	ListModuleUpdatePolicies(ctx context.Context, req *ListModuleUpdatePoliciesRequest) (*ListModuleUpdatePoliciesResponse, error)
	CreateModuleUpdatePolicy(ctx context.Context, req *CreateModuleUpdatePolicyRequest) (*CreateModuleUpdatePolicyResponse, error)
}

// RegisterSourcesAPITools registers generated MCP tools for SourcesAPI.
func RegisterSourcesAPITools(server *mcp.Server, impl SourcesAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterSourcesAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*ListModuleSourcesRequest, *ListModuleSourcesResponse]{
		Name:             "ListModuleSources",
		Title:            "List module sources",
		Description:      "List all ModuleSource resources — OCI registries from which Deckhouse pulls modules.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  SourcesAPI_ListModuleSources_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: SourcesAPI_ListModuleSources_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *ListModuleSourcesRequest { return &ListModuleSourcesRequest{} },
		NewResponse:      func() *ListModuleSourcesResponse { return &ListModuleSourcesResponse{} },
		Handler:          impl.ListModuleSources,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateModuleSourceRequest, *CreateModuleSourceResponse]{
		Name:             "CreateModuleSource",
		Title:            "Create module source",
		Description:      "Create a new ModuleSource pointing at an OCI registry. Returns already-exists error if a source with the same name is already defined.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  SourcesAPI_CreateModuleSource_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: SourcesAPI_CreateModuleSource_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *CreateModuleSourceRequest { return &CreateModuleSourceRequest{} },
		NewResponse:      func() *CreateModuleSourceResponse { return &CreateModuleSourceResponse{} },
		Handler:          impl.CreateModuleSource,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*ListModuleUpdatePoliciesRequest, *ListModuleUpdatePoliciesResponse]{
		Name:             "ListModuleUpdatePolicies",
		Title:            "List module update policies",
		Description:      "List all ModuleUpdatePolicy resources controlling auto-update behaviour for modules.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  SourcesAPI_ListModuleUpdatePolicies_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: SourcesAPI_ListModuleUpdatePolicies_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *ListModuleUpdatePoliciesRequest { return &ListModuleUpdatePoliciesRequest{} },
		NewResponse:      func() *ListModuleUpdatePoliciesResponse { return &ListModuleUpdatePoliciesResponse{} },
		Handler:          impl.ListModuleUpdatePolicies,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*CreateModuleUpdatePolicyRequest, *CreateModuleUpdatePolicyResponse]{
		Name:             "CreateModuleUpdatePolicy",
		Title:            "Create module update policy",
		Description:      "Create a new ModuleUpdatePolicy with the given update mode. Returns already-exists error if a policy with the same name is already defined.",
		Namespace:        "deckhouse",
		InputSchemaJSON:  SourcesAPI_CreateModuleUpdatePolicy_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: SourcesAPI_CreateModuleUpdatePolicy_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{},
		Icons:            nil,
		NewRequest:       func() *CreateModuleUpdatePolicyRequest { return &CreateModuleUpdatePolicyRequest{} },
		NewResponse:      func() *CreateModuleUpdatePolicyResponse { return &CreateModuleUpdatePolicyResponse{} },
		Handler:          impl.CreateModuleUpdatePolicy,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const SourcesAPI_ListModuleSources_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"description\":\"ListModuleSourcesRequest is empty — no filters.\",\"additionalProperties\":false}"

const SourcesAPI_ListModuleSources_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"sources\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"ModuleSource resource name.\",\"examples\":[\"deckhouse\",\"custom-modules\"]},\"registry\":{\"type\":\"string\",\"description\":\"OCI registry URI (spec.registry.repo).\",\"examples\":[\"registry.deckhouse.io/deckhouse/ce/modules\"]},\"status\":{\"type\":\"string\",\"description\":\"Human-readable status from status.message or status.syncTime.\",\"examples\":[\"example\"]}},\"description\":\"All ModuleSource resources in the cluster.\\n\\nDeckhouse ModuleSource resource — an OCI registry providing modules.\",\"examples\":[{\"name\":\"example\",\"registry\":\"example\",\"status\":\"example\"}],\"required\":[\"name\",\"registry\",\"status\"],\"additionalProperties\":false},\"description\":\"All ModuleSource resources in the cluster.\\n\\nDeckhouse ModuleSource resource — an OCI registry providing modules.\",\"examples\":[[{\"name\":\"example\",\"registry\":\"example\",\"status\":\"example\"}]]}},\"description\":\"ListModuleSourcesResponse contains all ModuleSource resources.\",\"examples\":[{\"sources\":[{\"name\":\"example\",\"registry\":\"example\",\"status\":\"example\"}]}],\"additionalProperties\":false}"

const SourcesAPI_CreateModuleSource_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"ModuleSource resource name.\",\"examples\":[\"custom-modules\"],\"minLength\":1},\"registry\":{\"type\":\"string\",\"description\":\"OCI registry URI to set in spec.registry.repo.\",\"examples\":[\"registry.example.com/modules\"],\"minLength\":1}},\"description\":\"CreateModuleSourceRequest contains the name and registry URI.\",\"examples\":[{\"name\":\"example\",\"registry\":\"example\"}],\"required\":[\"name\",\"registry\"],\"additionalProperties\":false}"

const SourcesAPI_CreateModuleSource_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"created\":{\"type\":\"boolean\",\"description\":\"Whether the ModuleSource was successfully created.\",\"examples\":[true]},\"name\":{\"type\":\"string\",\"description\":\"Name of the created ModuleSource (echo of the request).\",\"examples\":[\"example\"]}},\"description\":\"Result of the CreateModuleSource operation.\",\"examples\":[{\"created\":true,\"name\":\"example\"}],\"required\":[\"created\",\"name\"],\"additionalProperties\":false}"

const SourcesAPI_ListModuleUpdatePolicies_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"description\":\"ListModuleUpdatePoliciesRequest is empty — no filters.\",\"additionalProperties\":false}"

const SourcesAPI_ListModuleUpdatePolicies_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"policies\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"ModuleUpdatePolicy resource name.\",\"examples\":[\"auto\",\"manual\"]},\"updateMode\":{\"type\":\"string\",\"description\":\"Update mode from spec.update.mode.\",\"examples\":[\"Auto\",\"Manual\"]}},\"description\":\"All ModuleUpdatePolicy resources in the cluster.\\n\\nDeckhouse ModuleUpdatePolicy resource — auto-update policy for modules.\",\"examples\":[{\"name\":\"example\",\"updateMode\":\"example\"}],\"required\":[\"name\",\"updateMode\"],\"additionalProperties\":false},\"description\":\"All ModuleUpdatePolicy resources in the cluster.\\n\\nDeckhouse ModuleUpdatePolicy resource — auto-update policy for modules.\",\"examples\":[[{\"name\":\"example\",\"updateMode\":\"example\"}]]}},\"description\":\"ListModuleUpdatePoliciesResponse contains all ModuleUpdatePolicy resources.\",\"examples\":[{\"policies\":[{\"name\":\"example\",\"updateMode\":\"example\"}]}],\"additionalProperties\":false}"

const SourcesAPI_CreateModuleUpdatePolicy_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"description\":\"ModuleUpdatePolicy resource name.\",\"examples\":[\"auto\"],\"minLength\":1},\"updateMode\":{\"type\":\"string\",\"description\":\"Update mode to set in spec.update.mode.\",\"examples\":[\"Auto\",\"Manual\"],\"minLength\":1}},\"description\":\"CreateModuleUpdatePolicyRequest contains the name and update mode.\",\"examples\":[{\"name\":\"example\",\"updateMode\":\"example\"}],\"required\":[\"name\",\"updateMode\"],\"additionalProperties\":false}"

const SourcesAPI_CreateModuleUpdatePolicy_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"created\":{\"type\":\"boolean\",\"description\":\"Whether the ModuleUpdatePolicy was successfully created.\",\"examples\":[true]},\"name\":{\"type\":\"string\",\"description\":\"Name of the created ModuleUpdatePolicy (echo of the request).\",\"examples\":[\"example\"]}},\"description\":\"Result of the CreateModuleUpdatePolicy operation.\",\"examples\":[{\"created\":true,\"name\":\"example\"}],\"required\":[\"created\",\"name\"],\"additionalProperties\":false}"
